name: openfwi_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_2
  - pip=23.2.1=py39h06a4308_0
  - python=3.9.17=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.4.0
    - cachetools==5.3.1
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - cmake==3.27.2
    - contourpy==1.1.0
    - cycler==0.11.0
    - filelock==3.12.3
    - fonttools==4.42.1
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.57.0
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.1
    - iunets==0.1
    - jinja2==3.1.2
    - kiwisolver==1.4.5
    - lit==16.0.6
    - markdown==3.4.4
    - markupsafe==2.1.3
    - matplotlib==3.7.2
    - memcnn==1.5.2
    - mpmath==1.3.0
    - networkx==3.1
    - numpy==1.25.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - packaging==23.1
    - pandas==2.1.0
    - pathlib2==2.3.7.post1
    - pillow==10.0.0
    - protobuf==4.24.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - seaborn==0.12.2
    - simpleitk==2.2.1
    - six==1.16.0
    - sympy==1.12
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.1
    - torch==2.0.1
    - torchvision==0.15.2
    - tqdm==4.66.1
    - triton==2.0.0
    - typing-extensions==4.7.1
    - tzdata==2023.3
    - urllib3==1.26.16
    - werkzeug==2.3.7
    - zipp==3.16.2
